### ISSUE TITLE
Claiming interface: Access denied (insufficient permissions)

### ISSUE THREAD

**Issue by xeniagda** [dcuddeback/libusb-rs#19]
I was trying out the `read_device.rs` example but ran into a problem: when running the `configure_endpoint` function, `claim_interface` gave an `Error::Access` when ran. I suspect this might be a problem of OS X, but I am currently stuck. Any help would be greatly appreciated!

**Comment by oberien** [comment]
Did you try running it with elevated permissions? On linux I needed to run it with `sudo`, otherwise it's not able to detach the kernel driver from the device.
Otherwise, could you please provide a backtrace of where the access error happened?

**Comment by xeniagda** [comment]
It seems like it was me just being stupid, the USB device was already used by another process.
