### ISSUE TITLE
read_device example returns error on ArchLinux

### ISSUE THREAD

**Issue by mrcbax** [dcuddeback/libusb-rs#22]
libusb version: libusb-1.0.21-2-x86_64
Linux Kernel: x86_64 Linux 4.13.11-1-ARCH
2006 Motherboard USB2.0 Compatible
Intel chipset

Fails finding device.

lsusb info:
```
Bus 001 Device 010: ID 045e:02e6 Microsoft Corp. Wireless XBox Controller Dongle
```
read_device error:
```
./target/debug/read_device 1118 742
could not find device 045e:02e6
```

**Comment by mrcbax** [comment]
Also recompiled to release version. Same error.

**Comment by dcuddeback** [comment]
I don't really see how this is actionable. The example just calls functions provided by `libusb`, so you would get the same error if you use `libusb` directly. Closing since this doesn't suggest an issue in this library.
