### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by AJAnderson** [dcuddeback/libusb-rs#33]
Hi there,

This is the first and foremost library for interacting with libusb in Rust but it seems to be gathering dust. Are you still actively maintaining this at all?

**Comment by tarcieri** [comment]
Note: Unless we hear otherwise, we are going to officially start tracking this crate as unmaintained in the RustSec Advisory Database:

https://github.com/RustSec/advisory-db/pull/180
