### ISSUE TITLE
Transfer Ownership

### ISSUE THREAD

**Issue by fpagliughi** [dcuddeback/libusb-rs#39]
I'm aware of the repeated queries to this repo (@AJAnderson) and the various forks (@a1lien, etc), but no one else has come out and asked...

Is @dcuddeback available and willing to transfer ownership of this repository and the associated project on [crates.io](https://crates.io/crates/libusb)?

Ditto for [libusb.sys](https://github.com/dcuddeback/libusb-sys), and [libudev-rs](https://github.com/dcuddeback/libudev-rs), for that matter.

The goal would be to consolidate all the outstanding PR's and forks, and then proceed with a new async/await API for the asynchronous calls in libusb.

**Comment by ryankurte** [comment]
hey just following up on this, it'd be great to merge in some of the fixes and update these ^_^

**Comment by otavio** [comment]
Take look to rusb. This is what we have been using.

**Comment by fpagliughi** [comment]
Agreed, `rusb` is the way to go right now. I had some more ambitious ideas about building out the async API for the library, but didn't want to create yet another fork. That's currently on hold awaiting some funding, but I still hope it happens.

But really, I'm getting a little worried about the number of hardware-related Rust crates that have been abandoned and would gladly be maintained by new people if the owners would just transfer ownership.

**Comment by otavio** [comment]
Indeed; it is a shame. The `rusb` guy is very nice to work with.

I think that due to the age of Rust, this is expected. As it matures, we'll see more libraries to get more confidence and people will commit more to it. We've been moving many projects to Rust lately and I think it is getting there.
